### ISSUE TITLE
Support for Ivy

### ISSUE THREAD

**Issue by eddwin** [rubenCodeforges/ng-gapi#83] opened 2019-06-19 00:53 UTC
While trying out the new Ivy engine, when trying to compile I got the following:

`ERROR in There is no format with import statements in '{PATH}/node_modules/ng-gapi' entry-point.`

**Comment by rubenCodeforges** [comment] 2019-06-19 05:34
Strange as ng-gapi is not doing any rendering, maybe something is wrong with your imports ?

**Comment by eddwin** [comment] 2019-06-20 09:49
@rubenCodeforges  Just tried it out on another project with the same result, probably I'm doing something wrong.

My imports are: 

`
...
import {
  GoogleApiModule,
  NgGapiClientConfig,
  NG_GAPI_CONFIG,
} from 'ng-gapi';
...`

Then I do the config as described in the `README.md`

`const gapiClientConfig: NgGapiClientConfig = {
  client_id: '{CLIENTID}.apps.googleusercontent.com',
  discoveryDocs: [],
  scope: 'profile email'
};`

Import it as:

`
...,
GoogleApiModule.forRoot({
      provide: NG_GAPI_CONFIG,
      useValue: gapiClientConfig
    }),
  ],
...`

**Comment by rubenCodeforges** [comment] 2019-06-20 10:59
I think i this is related to https://github.com/angular/angular/issues/29564#issuecomment-477560300

**Comment by jrodrigueznorte** [comment] 2020-03-23 18:42
Hello i have this problem after update my project to angular 9 

![image](https://user-images.githubusercontent.com/49953224/77351443-8c628480-6d1c-11ea-86d0-6c696455a7b9.png)

this is my partial package.json 

`
"@angular/animations": "^9.0.7",
    "@angular/cdk": "^9.1.3",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/material": "^9.1.3",
    "@angular/platform-browser": "~9.0.7",
    "ng-gapi": "0.0.73"
`

**Comment by rubenCodeforges** [comment] 2020-03-23 18:44
@jrodrigueznorte i probably need to review the lib and update it , but im currently very occupied .
PR are welcomed

**Comment by argarner** [comment] 2020-03-28 04:36
For me, this only started with the latest Angular release (v9.1.0). A temporary immediate workaround is simply to disable ivy in your `tsconfig.json`, until the issue is resolved by the package owner.

```
"angularCompilerOptions": {
    "enableIvy": false,
}
```

**Comment by ocket8888** [comment] 2020-04-01 01:19
Angular has a guide for providers to update to be Ivy-compatible: https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic

**Comment by rubenCodeforges** [comment] 2020-04-01 09:01
@ocket8888 yes i can change that, but this will mean , previous versions will not work

**Comment by rubenCodeforges** [comment] 2020-04-01 10:49
Guys if some one can test the changes https://github.com/rubenCodeforges/ng-gapi/pull/97

**Comment by rubenCodeforges** [comment] 2020-04-01 11:35
@ocket8888 @jrodrigueznorte @argarner  Guys please test the `latest/v9` branch , if it works for you ill publish to npm

**Closed** 2020-04-29 19:22 UTC

**Comment by ocket8888** [comment] 2020-04-29 21:06
My project is having other problems, which I don't believe are directly related to this package. So, the error message has changed, but I can't tell you for sure whether or not that branch worked for me.

**Comment by argarner** [comment] 2020-04-29 22:18
Sorry didn't see your comment @rubenCodeforges. @ocket8888 I believe the older version also works with Ivy if you add `"postinstall": "ngcc"` to your package.json scripts, instead of disabling in tsconfig.json like my previous comment.

**Comment by ocket8888** [comment] 2020-04-29 22:22
Maybe, but if I'm blocked from upgrading to Angular 9 - which I currently am - then I'm not going to bother using Ivy.
