### ISSUE TITLE
Uncaught TypeError: gapi.client.HttpBatch is not a constructor

### ISSUE THREAD

**Issue by SCP002** [rubenCodeforges/ng-gapi#62] opened 2018-09-04 09:26 UTC
Readme describes a way to work with HttpBatch like this:
```ts
export class FooService {
    constructor(gapiService: GoogleApiService) {
        gapiService.onLoad().subscribe(()=> {
           const myBatch: HttpBatch = new HttpBatch();
           myBatch.add(
               // your request
           );
        });
    }
}
```

But for me it's unclear where HttpBatch reference come from.

---
If use alias:
```ts
import HttpBatch = gapi.client.HttpBatch;

// ...

const batch: HttpBatch = new HttpBatch();
```
I got 

> Uncaught ReferenceError: gapi is not defined

If use full path:
```ts
const batch: gapi.client.HttpBatch = new gapi.client.HttpBatch();
```
I got

> Uncaught TypeError: gapi.client.HttpBatch is not a constructor

---
Sure, it all happens even inside of gapiService.onLoad() subscribe callback.

How can this problem be solved?

Thanks in advance!

**Comment by rubenCodeforges** [comment] 2018-09-04 10:40
@SCP002 hey thanks for using my lib , checkout this https://github.com/rubenCodeforges/ng-gapi/issues/58 might be your case

**Comment by rubenCodeforges** [comment] 2018-09-04 10:41
Oh sorry , now i see , HttpBatch is from typings and is referenced through them to the libs batch

**Comment by SCP002** [comment] 2018-09-05 12:32
Don't want to annoy, but it means batch functionality not working currently?
I mean, is there any way to get HttpBatch object instance, or any workarounds?
Like access libs batch somehow or so. Since we can't use:
```ts
const batch = gapi.client.newBatch();
```

**Comment by rubenCodeforges** [comment] 2018-09-05 12:47
batch is working you just use it a bit differently 

```
 // inside the onload callback to make sure gapi is loaded
const batch: HttpBatch =  new HttpBatch();
batch.add();
```

it was tested even on the demo it was working . 

How do you do your imports , manual or IDE ?

**Comment by SCP002** [comment] 2018-09-05 13:09
Ah, I use VSCode currently.
However, it has no suggestions how HttpBatch should be imported.

---
<img width="1280" alt="ide" src="https://user-images.githubusercontent.com/22541678/45094952-78990280-b125-11e8-97ba-99c8c6732bcc.png">

---
So i just tried
```ts
const batch: gapi.client.HttpBatch = new gapi.client.HttpBatch();
```
But chrome console telling me
> Uncaught TypeError: gapi.client.HttpBatch is not a constructor

**Comment by rubenCodeforges** [comment] 2018-09-05 13:10
so this is the problem

**Comment by rubenCodeforges** [comment] 2018-09-05 13:56
btw what version are you using ?

**Comment by SCP002** [comment] 2018-09-06 09:05
Here is snippet of code with workaround:

```ts
const params: Object = {
    // ...
};

const body: Object = {
    // ...
};

gapi.load('client', () => {
    // @ts-ignore: Property 'newBatch' does not exist on type 'typeof client'.
    const batch: gapi.client.HttpBatch = gapi.client.newBatch();

    const options: gapi.client.RequestOptions = {
        path: 'REQUEST_PATH',
        method: 'REQUEST_METHOD',
        params: params,
        body: body
    };

    const request: gapi.client.HttpRequest<any> = gapi.client.request(options);

    batch.add(request);

    batch.execute((resMap: Object, resRaw: Object) => {
        console.log(resMap);
        console.log(resRaw);
    });
});
```

It worked for me.
Sure, this is not a solution, but hey, it's better than nothing.

Feel free to close this if you wish. Or, if any assistance needed, feel free to ask.

**Comment by rubenCodeforges** [comment] 2018-09-10 04:53
This is very strange , the problem is only in type declaration , could be that @types have been updated , i will recap on that.

**Comment by alpha1988** [comment] 2018-09-24 16:54
I also have this problem, but i don't know what i need to do with this.

**Comment by shahbazhaidry** [comment] 2018-10-01 13:14
> From package.json file:
> 
> ```json
> "@angular/core": "^6.1.0",
> "ng-gapi": "0.0.51",
> "rxjs": "^6.0.0",
> ```
> 
> Also probably it's worth mentioning that:
> 
> * I serve application during the development using AOT compilation (ng serve --aot).
> * All auth-related stuff works just fine (OAuth2).
> * This snippet of code fails too (and it's not related to HttpBatch directly):
> 
> ```ts
> this.gapiService.onLoad().subscribe(() => {
>     console.log('gapiService loaded...');
> 
>     const options: gapi.client.RequestOptions = {
>         path: 'youtube/v3/playlistItems',
>         method: 'POST',
>         params: params,
>         body: body
>     };
> 
>     const request: gapi.client.HttpRequest<any> = gapi.client.request(options);
> 
>     request.execute((response: Object) => {
>         console.log(response);
>     });
> });
> ```
> 
> With:
> 
> > Cannot read property 'request' of undefined
> 
> The only way I get it to work is using gapi.load('client', () => { ... }):
> 
> ```ts
> gapi.load('client', () => {
>     // Everything okay there.
> }
> ```



> Here is snippet of code with workaround:
> 
> ```ts
> const params: Object = {
>     // ...
> };
> 
> const body: Object = {
>     // ...
> };
> 
> gapi.load('client', () => {
>     // @ts-ignore: Property 'newBatch' does not exist on type 'typeof client'.
>     const batch: gapi.client.HttpBatch = gapi.client.newBatch();
> 
>     const options: gapi.client.RequestOptions = {
>         path: 'REQUEST_PATH',
>         method: 'REQUEST_METHOD',
>         params: params,
>         body: body
>     };
> 
>     const request: gapi.client.HttpRequest<any> = gapi.client.request(options);
> 
>     batch.add(request);
> 
>     batch.execute((resMap: Object, resRaw: Object) => {
>         console.log(resMap);
>         console.log(resRaw);
>     });
> });
> ```
> 
> It worked for me.
> Sure, this is not a solution, but hey, it's better than nothing.
> 
> Feel free to close this if you wish. Or, if any assistance needed, feel free to ask.

@SCP002 could you help me i am using same technology to get the analytics data
here is my code

 ngOnInit() { 
    
    gapi.load('client', () => {
        const batch:gapi.client.HttpBatch = gapi.client.newBatch();

        const options: gapi.client.RequestOptions = {
            path: 'https://analyticsreporting.googleapis.com/v4/reports:batchGet',
            method: 'POST',
            params: 'params',
            body: {
                reportRequests: [
                    {
                      "viewId": "xxxx",
                      "dateRanges":
                      [
                        {"endDate": "7daysAgo", "startDate": "today"}
                      ],
                      "metrics":
                      [
                        {"expression": "ga:users"}
                      ],
                      "dimensions":
                      [
                        {"name": "ga:userType"}
                      ]
                    }
                  ]
            }
        };

        const request: gapi.client.HttpRequest<any> = gapi.client.request(options);

        batch.add(request);
        
        console.log(request);

        batch.execute( ( resMap: object, resRaw: Object) => {
            console.log(resMap);
            console.log(resRaw);
        })
    })
  
  }

**Comment by SCP002** [comment] 2018-10-01 16:30
@shahbazhaidry Sure.

At first glance you just missing error suppression comment.
```
// @ts-ignore: Write some useful comment here.
```

In other words, this:
```ts
const batch:gapi.client.HttpBatch = gapi.client.newBatch();
```
Should look like this:
```ts
// @ts-ignore: Property 'newBatch' does not exist on type 'typeof client'.
const batch: gapi.client.HttpBatch = gapi.client.newBatch();
```
---
Explanation:
Ng-gapi uses javascript library by google + type definitions.
By some mysterious reasons, 'newBatch()' function is missing in typings. While, in fact, this function exist in library.
So currently we can simply suppress typescript error and in result everything should still work.

**Comment by shahbazhaidry** [comment] 2018-10-02 05:59
@SCP002 thanks for reply
i am getting this error code - 401 
code: 401
message: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
status: "UNAUTHENTICATED"

i have use this scope

"https://www.googleapis.com/auth/analytics",
      "https://www.googleapis.com/auth/analytics.readonly",

**Comment by rubenCodeforges** [comment] 2018-10-02 13:45
All the errors you get are api errors , they dont relate to ng-gapi.

```
const params: Object = {
// ...
};
```
Regarding this , i dont know what that is and where you got it.

I would advise you to read Google API Documentation.

**Comment by SCP002** [comment] 2018-10-02 15:11
@shahbazhaidry
> Since we are going off-topic heavily, I suggest you search / ask the same question at [stackoverflow](https://stackoverflow.com/).
> Perfect place for this type of questions, try it out. Most probably you will receive help.
---
@rubenCodeforges 
> My apologies for all this mess in comments. :worried:

**Comment by shahbazhaidry** [comment] 2018-10-03 09:48
@SCP002 @rubenCodeforges thanks for the reply
finally, it works i got data from analytics
thanks, guys for help

**Comment by rubenCodeforges** [comment] 2018-10-04 08:29
@SCP002 thanks for help. Closing this

**Closed by rubenCodeforges** 2018-10-04 08:29 UTC
Labels: bug
