### ISSUE TITLE
Cannot find module 'ng-gapi' / Cannot find namespace 'gapi' in Angular 9

### ISSUE THREAD

**Issue by kbtganesh** [rubenCodeforges/ng-gapi#102] opened 2020-07-02 13:17 UTC
I've just upgraded my Angular version from 7 to 9 as per the Angular Documentation.
I've also updated `ng-gapi` version from `0.0.43` to `0.0.93`. 

But when I do "ng serve", I am facing compiler errors saying `Cannot find module 'ng-gapi'` at import statement and `Cannot find namespace 'gapi'` at when trying to use `gapi.auth2.GoogleUser`.

Things I've tried
- Delete node_modules, clear cache, npm install again.
- added `"types": ["gapi.auth2"]` in `compilerOptions` of **tsconfig.js**
- Went through other similar issues #96  & #93 but nothing helped as they were addressing different issue.

Some said to disable ivy as a solution but I cannot do that. I need this to be working along with ivy.

**Version Details**

```
Angular CLI: 9.1.9
Node: 10.15.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.10
@angular-devkit/build-optimizer   0.901.10
@angular-devkit/build-webpack     0.901.10
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cdk                      9.2.4
@angular/cli                      9.1.9
@angular/material                 9.2.4
@ngtools/webpack                  9.1.10
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Error received in terminal**
```
ERROR in src/client/app/routes/rguestbook/rguestbook/ga-analytics/services/user-service.service.ts:3:35 - error TS2307: Cannot find module 'ng-gapi'.

3 import { GoogleAuthService } from "ng-gapi";
                                    ~~~~~~~~~
src/client/app/routes/rguestbook/rguestbook/ga-analytics/services/user-service.service.ts:4:21 - error TS2503: Cannot find namespace 'gapi'.

4 import GoogleUser = gapi.auth2.GoogleUser;
                      ~~~~
src/client/app/routes/rguestbook/rguestbook/ga-analytics/services/user-service.service.ts:5:21 - error TS2503: Cannot find namespace 'gapi'.

5 import GoogleAuth = gapi.auth2.GoogleAuth;
                      ~~~~
src/client/app/shared/shared.module.ts:28:8 - error TS2307: Cannot find module 'ng-gapi'.

28 } from "ng-gapi";
          ~~~~~~~~~
src/client/app/routes/rguestbook/rguestbook/ga-analytics/ga-analytics-dashboard/ga-analytics-dashboard.component.ts:5:34 - error TS2307: Cannot find module 'ng-gapi'.

5 import { GoogleApiService } from 'ng-gapi';
                                   ~~~~~~~~~
src/client/app/routes/rguestbook/rguestbook/ga-analytics/ga-analytics-dashboard/ga-analytics-dashboard.component.ts:7:20 - error TS2503: Cannot find namespace 'gapi'.

7 import HttpBatch = gapi.client.HttpBatch;

ERROR in ./src/client/app/routes/rguestbook/rguestbook/ga-analytics/ga-analytics-dashboard/ga-analytics-dashboard.component.ts
Module not found: Error: Can't resolve 'ng-gapi' in 'C:\Users\MuruganG\OneDrive - Agilysys, Inc\Documents\ADMINPORTAL\src\client\app\routes\rguestbook\rguestbook\ga-analytics\ga-analytics-dashboard'
ERROR in ./src/client/app/routes/rguestbook/rguestbook/ga-analytics/services/user-service.service.ts
Module not found: Error: Can't resolve 'ng-gapi' in 'C:\Users\MuruganG\OneDrive - Agilysys, Inc\Documents\ADMINPORTAL\src\client\app\routes\rguestbook\rguestbook\ga-analytics\services'
ERROR in ./src/client/app/shared/shared.module.ts
Module not found: Error: Can't resolve 'ng-gapi' in 'C:\Users\MuruganG\OneDrive - Agilysys, Inc\Documents\ADMINPORTAL\src\client\app\shared'
```

Not sure what's causing this issue.

**Comment by rubenCodeforges** [comment] 2020-07-02 14:23
Hi , its a known issue , will be fixes soon

**Comment by kbtganesh** [comment] 2020-07-02 14:41
Hi @rubenCodeforges , thanks for the response. Do we have any workarounds? When shall we expect the fix?

**Comment by rubenCodeforges** [comment] 2020-07-03 11:40
The only workaround is to disable ivy , a fix might be available after this weekend , im very busy at work right now and have 0 free time , hope things will change after weekend

**Comment by vaughnmuirhead** [comment] 2020-07-06 06:33
Very keen to get a fix on this. Is there anything I can do to assist?

**Comment by rubenCodeforges** [comment] 2020-07-06 06:35
@vaughnmuirhead check the last comment https://github.com/rubenCodeforges/ng-gapi/issues/96

Closing due to duplicate of #96

**Closed by rubenCodeforges** 2020-07-06 06:35 UTC
Labels: bug
